name: Mirror to GitLab

on:
  push:
    branches: [ '**' ]
  delete:
    branches: [ '**' ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push mirror to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_MIRROR_TOKEN }}@gitlab.com/dan.missud-group/SpaceBackGroundBuilder.git
          git push gitlab --mirror
